name: Sauce Labs Tests

on:
  push:
    branches:
      - main

# on: ........
#   pull_request:
#     branches:
#       - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Prepare test build
        run: |
          chmod +x prepareTestBuild.sh
          ./prepareTestBuild.sh

      - name: Install dependencies
        run: npm install

      - name: List generated files
        run: |
          ls -R

      - name: Upload IPA to Sauce Labs
      id: upload-ipa
      run: |
        response=$(curl -u ${{ secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }} \
          -X POST \
          -H "Content-Type: application/octet-stream" \
          --data-binary DemoApp1-main/AppsToTest-rdc/DemoApp1UITests-Runner.ipa \
          "https://api.us-west-1.saucelabs.com/v1/storage/upload?name=DemoApp1UITests-Runner.ipa")
        echo "Storage response: $response"
        app_id=$(echo $response | jq -r .item.id)
        echo "App ID: $app_id"
        echo "APP_ID=$app_id" >> $GITHUB_ENV

    - name: Trigger XCUITest on Sauce Labs
      run: |
        curl -u ${{secrets.SAUCE_USERNAME }}:${{ secrets.SAUCE_ACCESS_KEY }} \
        -X POST \
        -H "Content-Type: application/json" \
        -d '{
              "devices": [{"name": "iPhone.*", "platformVersion": "14"}],
              "app": "sauce-storage:${{ env.APP_ID }}",
              "testFramework": "xcuitest",
              "testName": "My XCUITest",
              "suites": ["YourTestSuite"],
              "platformName": "iOS"
            }' \
        "https://api.us-west-1.saucelabs.com/v1/test/xcuitest"
